# mypy: ignore-errors
# ruff: noqa: INP001
"""Customer model.

Revision ID: a36620ab7c6e
Revises: c5615d9526b0
Create Date: 2025-11-02 16:49:51.417075

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a36620ab7c6e"
down_revision: str | None = "c5615d9526b0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "CHECKING",
        "BOT_350",
        "BOT_800",
        "BOT_1300",
        "BOT_5000",
        "FAMILY_VIEW_100",
        "HUB",
        "TRADE_BAN",
        "BOT_ANTI_KT",
        "DOUBLE_SUBSTITUTION",
        "SUCCESS",
        name="errorstatus",
    ).create(op.get_bind())
    op.create_table(
        "customers",
        sa.Column(
            "id", sa.Integer(), sa.Identity(always=False), nullable=False
        ),
        sa.Column("hub_id", sa.Integer(), nullable=False),
        sa.Column(
            "original_steam_connected",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "second_steam_connected",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "error_status",
            postgresql.ENUM(
                "CHECKING",
                "BOT_350",
                "BOT_800",
                "BOT_1300",
                "BOT_5000",
                "FAMILY_VIEW_100",
                "HUB",
                "TRADE_BAN",
                "BOT_ANTI_KT",
                "DOUBLE_SUBSTITUTION",
                "SUCCESS",
                name="errorstatus",
                inherit_schema=True,
                create_type=False,
            ),
            server_default="CHECKING",
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk__customers__user_id__users"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__customers")),
        sa.UniqueConstraint("hub_id", name=op.f("uq__customers__hub_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("customers")
    sa.Enum(
        "CHECKING",
        "BOT_350",
        "BOT_800",
        "BOT_1300",
        "BOT_5000",
        "FAMILY_VIEW_100",
        "HUB",
        "TRADE_BAN",
        "BOT_ANTI_KT",
        "DOUBLE_SUBSTITUTION",
        "SUCCESS",
        name="errorstatus",
    ).drop(op.get_bind())
    # ### end Alembic commands ###
