# mypy: ignore-errors
# ruff: noqa: INP001
"""customers index to second_steam_connected.

Revision ID: 726a7fff0f00
Revises: 0ca2c75661ff
Create Date: 2025-11-04 04:21:01.997979

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "726a7fff0f00"
down_revision: str | None = "0ca2c75661ff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix__customers__second_steam_connected"),
        "customers",
        ["second_steam_connected"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix__customers__second_steam_connected"), table_name="customers"
    )
    # ### end Alembic commands ###
