# mypy: ignore-errors
# ruff: noqa: INP001
"""Chat Room and Chat Message models.

Revision ID: 0ca2c75661ff
Revises: a36620ab7c6e
Create Date: 2025-11-02 23:56:02.948139

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0ca2c75661ff"
down_revision: str | None = "a36620ab7c6e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("CUSTOMER", "ADMIN", name="authortype").create(op.get_bind())
    op.create_table(
        "chat_rooms",
        sa.Column(
            "id", sa.Integer(), sa.Identity(always=False), nullable=False
        ),
        sa.Column(
            "is_customer_in_chat",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk__chat_rooms__customer_id__customers"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__chat_rooms")),
    )
    op.create_table(
        "chat_messages",
        sa.Column(
            "id", sa.Integer(), sa.Identity(always=False), nullable=False
        ),
        sa.Column("chat_room_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column(
            "author_type",
            postgresql.ENUM(
                "CUSTOMER",
                "ADMIN",
                name="authortype",
                inherit_schema=True,
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["chat_room_id"],
            ["chat_rooms.id"],
            name=op.f("fk__chat_messages__chat_room_id__chat_rooms"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__chat_messages")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chat_messages")
    op.drop_table("chat_rooms")
    sa.Enum("CUSTOMER", "ADMIN", name="authortype").drop(op.get_bind())
    # ### end Alembic commands ###
