# mypy: ignore-errors
# ruff: noqa: INP001
"""Invite code model.

Revision ID: 59de69851005
Revises: f1d4d42788a3
Create Date: 2025-11-02 15:50:48.993242

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "59de69851005"
down_revision: str | None = "f1d4d42788a3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invite_codes",
        sa.Column(
            "id", sa.Integer(), sa.Identity(always=False), nullable=False
        ),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__invite_codes")),
        sa.UniqueConstraint("code", name=op.f("uq__invite_codes__code")),
    )
    op.drop_constraint(
        op.f("fk__sessions__user_id__users"), "sessions", type_="foreignkey"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("fk__sessions__user_id__users"),
        "sessions",
        "users",
        ["user_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_table("invite_codes")
    # ### end Alembic commands ###
